export default {
  /* ACTIONS */
  CHANGE_CURRENT_INPUT: Symbol("CHANGE_CURRENT_INPUT"),
  EXPAND: Symbol("EXPAND"),
  PROMPT: Symbol("PROMPT"),
  BLUR_INPUT: Symbol("BLUR_INPUT"),
  EXEC_COMMAND: Symbol("EXEC_COMMAND"),
  NAVIGATE_LIST: Symbol("NAVIGATE_LIST"),
  NAVIGATE_BACKWARD: Symbol("NAVIGATE_BACKWARD"),
  SET_LOADER: Symbol("NAVIGATE_BACKWARD"),
  RECEIVE_COMMAND_RESULTS: Symbol("RECEIVE_COMMAND_RESULTS"),
  SET_ACTIVE_ITEM_INDEX: Symbol("SET_ACTIVE_ITEM_INDEX"),
  ADD_ACTIVE_ITEM_TO_SELECTION: Symbol("ADD_ACTIVE_ITEM_TO_SELECTION"),
  /* MISC */
  DOWN: Symbol("DOWN"),
  UP: Symbol("UP"),
};
